modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"

[[mods]]
modId="o123456789"
version="${version}"
displayName="O123456789"
authors="catboybinary"
description='''
This mod changes the item count numbers to those from Create mod
'''
logoFile="title.png"

[[dependencies.o123456789]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"
[[dependencies.o123456789]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="CLIENT"
